# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbfd5a1898900becd8f3ac111502d6f214a51e4185394a84878c38eaafa514c8c72da5eb18268e0d2f9dfac68fe26f9a7670a266c38579c90e3d316144650f7f

test:
  secret_key_base: 14e270d18f245fe5a92a24bfe4005a229b11f7be55a0c45c6f23440833ad6f2fbd1bd01b720d962b393301072c01108ccf12f6caa353d61ee8e5e68452e39cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
